name: FasterMinecart
version: 1.0
main: de.findus1994.FasterMinecart.Main
author: Findus1994
description: A plugin to increase the speed of a Minecart. 

commands:
    speedme:
        usage: /<command>
        description: Speed up a minecart
    slowme:
        usage: /<command>
        description: Slow down a minecart